### ISSUE TITLE
BUG: Drop Shadow degrades quality of the tile. Blurs it.

### ISSUE THREAD

**Issue by baileywick** [Feu-Secret/Tokenmagic#232] opened 2022-12-11 18:33 UTC
Whenever the Drop Shadow filter is applied, using any settings, it appears to blur the tile it's applied to, degrading the quality of it. Not sure if there is anything to do about this.
![drop-shadow](https://user-images.githubusercontent.com/14203358/206922073-46c0b58b-b454-4c9c-8889-b2009884895d.png)

**Comment by LukasPrism** [comment] 2023-01-19 01:11
Would love to see this fixed so Flying Tokens module doesn't result in blurry tokens

**Comment by Aedif** [comment] 2023-02-10 19:49
> Would love to see this fixed so Flying Tokens module doesn't result in blurry tokens

Does it happen only on specific tiles/tokens? I'm not noticing this at all 🤔

**Comment by baileywick** [comment] 2023-02-10 20:19
I've had trouble replicating this since posting. I don't know if it was a
module conflict or something else, but it seems to be corrected now.

**Comment by Aedif** [comment] 2023-04-29 10:36
As I am unable to reproduce it and the reporter hasn't seen it since either I'm closing the issue.

Feel free to re-open it if you come across it again.

**Closed by Aedif** 2023-04-29 10:36 UTC
Labels: bug

**Comment by LukasPrism** [comment] 2023-04-29 10:59
I just got pinged about this and it reminded me to take a look. I know how to reproduce it now – you need to have the core setting Pixel Ratio Resolution Scaling on (on a high dpi monitor).

What it looks like is happening is the token is excluded from the scaling – so it will be blurry as if the scaling is turned off. When I turn off scaling basically the whole canvas looks as blurry as the token with the drop shadow TMFX.

Here's the scene with scaling off:
<img width="312" alt="Screenshot 2023-04-29 at 10 56 32 PM" src="https://user-images.githubusercontent.com/104886594/235299036-eeb231bf-e78e-468c-bf96-7a27f3c5a96f.png">

Scaling on:
<img width="363" alt="Screenshot 2023-04-29 at 10 55 05 PM" src="https://user-images.githubusercontent.com/104886594/235299073-872ee4f4-43f5-48e1-884d-d2ac0e7ab0f0.png">

Scaling on with drop shadow on the selected token:
<img width="333" alt="Screenshot 2023-04-29 at 10 54 07 PM" src="https://user-images.githubusercontent.com/104886594/235299092-992610f5-4cca-443a-85b3-010d049501e3.png">

Not sure if there's anything you want to do about this... would only affect those with high-dpi screens. I'm using a MacBook so noticed it.

**Comment by Aedif** [comment] 2023-05-03 13:27
Should be resolved in release v0.6.3
