### ISSUE TITLE
Feature Request: Override export/import

### ISSUE THREAD

**Issue by siliconsaint** [Feu-Secret/Tokenmagic#140] opened 2021-06-23 20:44 UTC
Our group is using TMFX to handle over 35 overrides at this point. We're juggling that across 5-6 worlds. Is it possible to get an export/import function for configurations for the entire templates settings feature?

**Comment by Feu-Secret** [comment] 2021-06-24 13:11
duplicate of #63

**Comment by Feu-Secret** [comment] 2021-06-24 13:13
Extract from the readme... :smile:
------------------------------------------------------------
Automatic template settings are linked to a world. You can import and export the settings with the following code :

To export your template settings in a json file

`TokenMagic.exportTemplateSettings(optional <exportName>);`

To import template settings from a json file (open a file picker dialog). Warning : your settings are REPLACED ! Before, you may want to save your data with the code above.

`(async) TokenMagic.importTemplateSettings();`

**Closed by Feu-Secret** 2021-06-24 13:13 UTC
Labels: duplicate
