### ISSUE TITLE
Suggestion: Settings menu and template visibility

### ISSUE THREAD

**Issue by MSAbaddon** [Feu-Secret/Tokenmagic#82] opened 2021-01-19 15:33 UTC
Hi,
thanks for this great module, I really love it.

Some suggestions for further improvement:
- Improved settings menu for templates. If you use a lot of overrides (e.g. a separate unique image for every template spell) the list of overrides gets quite long and confusing. Possible solutions: options for filtering and sorting, collapsing the actual settings of an overwrite until it is selected, ...
- It would be great if the hover over visibility of a templates' grid could be activated without the necessity of switching to the templates layer, e.g. using a definable key binding
- It would be great if not only the grid template but also the template border could be hidden

**Comment by dev7355608** [comment] 2021-01-19 19:02
> It would be great if not only the grid template but also the template border could be hidden

Duplicate of #78, but it's coming in the next release.

> It would be great if the hover over visibility of a templates' grid could be activated without the necessity of switching to the templates layer, e.g. using a definable key binding

Not a fan of key bindings, but I did a quick test and simply changed the hover behavior. This is the result: 

![templates](https://user-images.githubusercontent.com/31905376/105079790-34a5be80-5a90-11eb-9700-27c6a4090c7a.gif)

**Comment by MSAbaddon** [comment] 2021-01-19 19:39
That's awesome :-)

**Comment by Feu-Secret** [comment] 2021-04-26 19:36
Done.

**Closed by Feu-Secret** 2021-04-26 19:36 UTC
Labels: enhancement
