### ISSUE TITLE
All "transform" filters make a token appear blank

### ISSUE THREAD

**Issue by Ssezra** [Feu-Secret/Tokenmagic#111] opened 2021-04-23 15:00 UTC
When applying any of the "transform" filters (ie buldge, pinch, dodge, evade, saving roll, moo moo, twist, etc) the selected token disappears and the space becomes blank. When the delete filter is applied the token comes back as normal.
No animation or effect is played on execute.

**Comment by dev7355608** [comment] 2021-04-23 15:29
You use a Mac, right?

**Comment by Ssezra** [comment] 2021-04-23 15:36
I was recently just testing this from a Mac.  I just now remoted into a windows PC and the filters seem to work correctly on a windows box.  What would be the issue with Mac?

**Comment by dev7355608** [comment] 2021-04-23 15:44
It's a macOS-only issue. Duplicate of #45. It should be fixed in the next release.

**Closed by dev7355608** 2021-04-23 15:44 UTC
Labels: duplicate
